function extractOutermostJson(text) {
  const first = text.indexOf("{");
  const last = text.lastIndexOf("}");
  if (first >= 0 && last > first) return text.substring(first, last + 1);
  return text;
}

export async function invokeGeminiEvaluation({
  transcript, patient_summary, recommendation, next_steps, findings, overall_disposition, extraction
}) {
  const apiKey = process.env.GEMINI_API_KEY;
  const model = process.env.GEMINI_MODEL || "gemini-2.5-flash-lite";
  if (!apiKey) throw new Error("Gemini API key not configured");

  const stepsText = (next_steps && next_steps.length) ? next_steps.map(s => `- ${s}`).join("\n") : "(none)";
  const findingsText = (findings && findings.length)
    ? findings.map(f => `- ${f.sop_id} [${f.status}]: ${f.finding} | action: ${f.action}`).join("\n")
    : "(none)";
  const dispText = overall_disposition ? `${overall_disposition.status} - ${overall_disposition.reason}` : "(unknown)";
  const extractionText = extraction ? JSON.stringify(extraction, null, 2) : "(extraction unavailable)";

  const systemInstruction = `You are a clinical quality evaluator for Premier Health's Care Specialist Console.
Your job is to evaluate the quality of AI-generated recommendations and next steps produced from patient call transcripts.

You will receive:
1. The extracted clinical flags from the transcript
2. The SOP findings that applied to this case
3. The recommendation and next steps generated by the analyzer

Evaluate across FOUR dimensions and return ONLY valid JSON.

DIMENSION 1 - SOP Accuracy (0.0 to 1.0)
Did the recommendation correctly apply the SOP rules?
- 1.0 = All applicable SOP rules were triggered correctly, none were missed
- 0.7 = Most rules applied correctly, minor omission or ambiguity
- 0.4 = A relevant SOP rule was missed or incorrectly applied
- 0.0 = Recommendation contradicts the SOPs entirely

INCOMPLETE TRANSCRIPT RULE:
If extraction_metadata.extraction_confidence is "low" OR extraction_metadata.null_flag_count > 3, the correct SOP output is an EMPTY sop_recommendations array with requires_human_review: true. A tool that generates routing recommendations from incomplete data is more dangerous than one that defers. If the analyzer generated sop_recommendations OR concrete next_steps when those incompleteness conditions were met, score SOP Accuracy LOW (<= 0.4) and set needs_escalation: true with a clear escalation_reason. A rule that fires when its triggering flag is null (treating null as false) is the same failure mode - penalize it the same way.

DIMENSION 2 - Extraction Completeness (0.0 to 1.0)
Were the clinical flags extracted accurately and completely?
- 1.0 = All relevant flags extracted with high confidence and source quotes
- 0.7 = Most flags extracted, 1-2 fields null where data was present
- 0.4 = Several flags missing or extracted with low confidence
- 0.0 = Critical flags missing entirely

DIMENSION 3 - Next Step Actionability (0.0 to 1.0)
Are the next steps specific, actionable, and appropriately prioritized?
- 1.0 = Each next step is specific, assigned a priority, and directly tied to an SOP rule
- 0.7 = Next steps are correct but lack specificity or priority ordering
- 0.4 = Next steps are vague or not directly tied to extracted flags
- 0.0 = Next steps are missing, incorrect, or contradictory

DIMENSION 4 - Human Review Appropriateness (0.0 to 1.0)
Was the requires_human_review flag set correctly?
- 1.0 = Flag correctly set given confidence levels and missing fields
- 0.5 = Flag set but review_reason is missing or unclear
- 0.0 = Flag incorrectly set (should have triggered but did not, or vice versa)

SCORING RULES:
- Score each dimension independently
- Provide a brief reason (1 sentence) for each score
- Compute overall_score as weighted average:
    SOP Accuracy:             40%
    Extraction Completeness:  30%
    Next Step Actionability:  20%
    Human Review:             10%
- score_label: "High" when overall_score >= 0.76; "Medium" when 0.51-0.75; "Low" when <= 0.50.
- Flag needs_escalation as true if SOP Accuracy < 0.6 OR Extraction Completeness < 0.5.
- Return ONLY valid JSON, no preamble, no markdown.

OUTPUT SCHEMA:
{
  "evaluation": {
    "sop_accuracy": { "score": float, "reason": "string" },
    "extraction_completeness": { "score": float, "reason": "string" },
    "next_step_actionability": { "score": float, "reason": "string" },
    "human_review_appropriateness": { "score": float, "reason": "string" },
    "overall_score": float,
    "score_label": "High | Medium | Low",
    "needs_escalation": boolean,
    "escalation_reason": "string | null",
    "evaluator_notes": "string | null"
  }
}`;

  const userText = `EXTRACTED CLINICAL FLAGS:
${extractionText}

APPLICABLE SOP FINDINGS:
${findingsText}

OVERALL DISPOSITION: ${dispText}

PATIENT SUMMARY (analyzer output):
${patient_summary || "(empty)"}

RECOMMENDATION TO EVALUATE:
${recommendation || "(empty)"}

NEXT STEPS TO EVALUATE:
${stepsText}

TRANSCRIPT (for grounding):
${transcript || "(empty)"}`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 25000);

  let respJson;
  try {
    const resp = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: systemInstruction }] },
        contents: [{ role: "user", parts: [{ text: userText }] }],
        generationConfig: { responseMimeType: "application/json", temperature: 0.2 }
      }),
      signal: controller.signal
    });

    if (!resp.ok) {
      const errBody = await resp.text();
      throw new Error(`Gemini API error: ${resp.status} ${resp.statusText}. Body: ${errBody}`);
    }
    respJson = await resp.json();
  } catch (e) {
    if (e.name === "AbortError") throw new Error("Gemini evaluation timed out after 25s");
    throw e;
  } finally {
    clearTimeout(timeoutId);
  }
  const text = respJson.candidates?.[0]?.content?.parts?.[0]?.text || "";
  const cleaned = extractOutermostJson(text).trim();
  const parsed = JSON.parse(cleaned);
  return { evaluation: parsed.evaluation, model };
}
