function extractOutermostJson(text) {
  const first = text.indexOf("{");
  const last = text.lastIndexOf("}");
  if (first >= 0 && last > first) return text.substring(first, last + 1);
  return text;
}

export async function invokeGeminiEvaluation({
  transcript, patient_summary, recommendation, next_steps, findings, overall_disposition, extraction
}) {
  const apiKey = process.env.GEMINI_API_KEY;
  const model = process.env.GEMINI_MODEL || "gemini-2.5-flash-lite";
  if (!apiKey) throw new Error("Gemini API key not configured");

  // Pass the analyzer output as literal JSON so Gemini reads exact field
  // values instead of paraphrased strings. Past failure: when the user
  // message said "OVERALL DISPOSITION: Ineligible - ...", Gemini sometimes
  // fabricated a different status in its complaint. JSON forces it to quote.
  const analyzerOutput = JSON.stringify({
    overall_disposition: overall_disposition || null,
    findings: findings || [],
    next_steps: next_steps || [],
    recommendation: recommendation || "",
    patient_summary: patient_summary || ""
  }, null, 2);
  const extractionText = extraction ? JSON.stringify(extraction, null, 2) : "(extraction unavailable)";

  const systemInstruction = `You are a clinical quality evaluator for Premier Health's Care Specialist Console.
Your job is to evaluate the quality of AI-generated recommendations and next steps produced from patient call transcripts.

You will receive:
1. The extracted clinical flags from the transcript
2. The SOP findings that applied to this case
3. The recommendation and next steps generated by the analyzer

Evaluate across FOUR dimensions and return ONLY valid JSON.

DIMENSION 1 - SOP Accuracy (0.0 to 1.0)
Did the recommendation correctly apply the SOP rules?
- 1.0 = All applicable SOP rules were triggered correctly, none were missed
- 0.7 = Most rules applied correctly, minor omission or ambiguity
- 0.4 = A relevant SOP rule was missed or incorrectly applied
- 0.0 = Recommendation contradicts the SOPs entirely

DISPOSITION PRIORITY TABLE (NON-NEGOTIABLE):
Pending - Callback Required (0) > Ineligible (1) > Deferred (2) > High Complexity (3) > Review (4) > Revision Case (5) > Hold (6) > Action Required (7). Lower number = more blocking. When multiple findings fire, overall_disposition.status MUST equal the case_status of the finding with the LOWEST priority number. This is a hard rule encoded in sops.json#status_priority.

DO NOT downgrade SOP Accuracy on the grounds that "a different rule should have driven the disposition because it is clinically more urgent." Clinical-urgency re-prioritization is OUT OF SCOPE for this evaluator - the priority table is the law. Examples of complaints that are INVALID and must NOT appear in your reason field:
- "The analyzer incorrectly prioritized [Ineligible rule] over [High Complexity rule]" - Ineligible (1) is more blocking than High Complexity (3) by the table; this is correct.
- "Rule X should also be addressed even if the patient is ineligible" - if Rule X is in the findings array and named in the recommendation, it has been addressed. The disposition reflects the most-blocking single status, not a clinical synthesis of all findings.
- "Rule X is clinically more critical than Rule Y" - irrelevant; the table decides.

Penalize ONLY when (a) a fired rule's case_status is wrong, (b) the disposition does not equal the case_status of the lowest-priority-number finding, (c) a rule fires on null required_flag values, or (d) a rule is missing in findings despite explicit transcript evidence that satisfies its trigger_logic.

EVIDENCE-QUOTING RULE (anti-hallucination):
The analyzer output is provided as literal JSON. Before raising ANY complaint about a structured field (overall_disposition.status, findings[i].sop_id, next_steps[i], etc.), you MUST quote the exact literal value from that JSON in your reason field. If you cannot quote it - if you only think the analyzer "should have said" something - the complaint is INVALID and you cannot use it as grounds for a penalty. Examples:
- VALID: "The JSON shows overall_disposition.status: 'High Complexity' but findings include JNT-002 (Ineligible, priority 1) which should drive the disposition by the priority table." (Quotes the actual value.)
- INVALID: "The overall_disposition.status was 'High Complexity' instead of 'Ineligible'" - if you did not quote the literal "High Complexity" value seen in the input JSON, this is fabricated. Do not write it.
- INVALID: "The analyzer reported X" without showing X verbatim from the JSON.

Do not paraphrase the analyzer's fields when discussing them. Quote first, then critique.

SCORE-MUST-MATCH-REASON RULE (sop_accuracy specifically):
The sop_accuracy.score and sop_accuracy.reason fields are coupled. Before writing a score below 1.0, your reason text MUST name at least one of the valid penalty grounds (a/b/c/d) from the list above AND quote the literal JSON value that violated it. If your reason text describes the analyzer's output as correct - phrases like "correctly identified and applied," "correctly reflects the priority table," "disposition correctly reflects," "no missed rules," "matches the priority table" - then the score MUST be 1.0. You may not write "the analyzer was correct" and then score 0.7, 0.8, or 0.9. A score below 1.0 is a claim that the analyzer made a specific mistake, and that claim must be named in the reason.

Examples that are FORBIDDEN:
- Reason: "The analyzer correctly identified and applied JNT-002 and JNT-004, and the disposition correctly reflects the priority table." Score: 0.7. -> INVALID. Reason praises the output; score must be 1.0.
- Reason: "Most rules applied correctly." Score: 0.85. -> INVALID. "Most" without naming which one failed is not a penalty ground.

Stylistic preferences (more concise wording, different phrasing, longer summary) are NOT penalty grounds and never justify reducing sop_accuracy.

UNRESOLVABLE SEMANTICS (so you don't misread the unresolvable array):
A rule is "unresolvable" if and ONLY if the analyzer did NOT fire it AND at least one of its required_flags is null in the extraction. By definition, a rule that appears in findings/sop_recommendations CANNOT also be in unresolvable - firing means the required_flags had concrete non-null values. INVALID complaint that must not appear in your reasons:
- "rule X should be moved to unresolvable" - if X is in findings, its data was confirmed; unresolvable is wrong for it.
- "the flag for rule X should be in unresolvable" - unresolvable lists rule ids, not flag names, and only for rules the analyzer DID NOT fire.

INTEGRATION CHECK (so you don't falsely claim a rule was dropped):
A rule is "fully integrated" when (1) it is in findings[], (2) it is referenced by SOP id in recommendation, AND (3) at least one entry in next_steps[] is prefixed with its SOP id in brackets. Before you write "rule X was not integrated into the next steps", verify all three points. If all three are present, that complaint is INVALID and must not appear in your reason. The presence of OTHER findings in next_steps does NOT mean rule X was dropped - check for [X] prefix specifically.

INCOMPLETE TRANSCRIPT RULE:
If extraction_metadata.extraction_confidence is "low" OR extraction_metadata.null_flag_count > 3, the correct SOP output is an EMPTY sop_recommendations array with requires_human_review: true. A tool that generates routing recommendations from incomplete data is more dangerous than one that defers. If the analyzer generated sop_recommendations OR concrete next_steps when those incompleteness conditions were met, score SOP Accuracy LOW (<= 0.4) and set needs_escalation: true with a clear escalation_reason. A rule that fires when its triggering flag is null (treating null as false) is the same failure mode - penalize it the same way.

INCOMPLETE TRANSCRIPT SCORING RULES (more specific guidance):
When extraction_metadata.null_flag_count >= 3 OR extraction_metadata.requires_human_review is true, the correct analyzer output is:

1. overall_disposition.status MUST be "Pending - Callback Required" - NOT "Ineligible", "Deferred", or any other actionable status. Rationale: Ineligible means a rule fired on confirmed data. Pending means data is missing. These are different states.

2. SOP rules whose required_flags are null MUST appear in an "unresolvable" array on the analyzer output, NOT in sop_recommendations. Rationale: A recommendation implies the system evaluated the rule. It cannot evaluate what it cannot read.

3. Score sop_accuracy as a MAXIMUM of 0.75 if any rule appears in sop_recommendations whose required_flag values include null. The rule did not fire correctly - it fired prematurely.

4. The correct output for an incomplete transcript is:
   - sop_recommendations: [] (or only rules whose required_flags are all non-null)
   - unresolvable: [list of rule ids that cannot be evaluated]
   - overall_disposition.status: "Pending - Callback Required"
   - extraction_metadata.requires_human_review: true
   - next_steps: e.g. "Send follow-up questionnaire covering PT history, opioid use, HbA1c, dental visit"

DIMENSION 2 - Extraction Completeness (0.0 to 1.0)
Were the clinical flags extracted accurately and completely?
- 1.0 = All relevant flags extracted with high confidence and source quotes
- 0.7 = Most flags extracted, 1-2 fields null where data was present
- 0.4 = Several flags missing or extracted with low confidence
- 0.0 = Critical flags missing entirely

DIMENSION 3 - Next Step Actionability (0.0 to 1.0)
Are the next steps specific, actionable, and appropriately prioritized?
- 1.0 = Each next step is specific, assigned a priority, and directly tied to an SOP rule
- 0.7 = Next steps are correct but lack specificity or priority ordering
- 0.4 = Next steps are vague or not directly tied to extracted flags
- 0.0 = Next steps are missing, incorrect, or contradictory

DIMENSION 4 - Human Review Appropriateness (0.0 to 1.0)
Was the requires_human_review flag set correctly?
- 1.0 = Flag correctly set given confidence levels and missing fields
- 0.5 = Flag set but review_reason is missing or unclear
- 0.0 = Flag incorrectly set (should have triggered but did not, or vice versa)

SCORING RULES:
- Score each dimension independently
- Provide a brief reason (1 sentence) for each score
- Compute overall_score as weighted average:
    SOP Accuracy:             40%
    Extraction Completeness:  30%
    Next Step Actionability:  20%
    Human Review:             10%
- score_label: "High" when overall_score >= 0.76; "Medium" when 0.51-0.75; "Low" when <= 0.50.
- Flag needs_escalation as true if SOP Accuracy < 0.6 OR Extraction Completeness < 0.5.
- Return ONLY valid JSON, no preamble, no markdown.

OUTPUT SCHEMA:
{
  "evaluation": {
    "sop_accuracy": { "score": float, "reason": "string" },
    "extraction_completeness": { "score": float, "reason": "string" },
    "next_step_actionability": { "score": float, "reason": "string" },
    "human_review_appropriateness": { "score": float, "reason": "string" },
    "overall_score": float,
    "score_label": "High | Medium | Low",
    "needs_escalation": boolean,
    "escalation_reason": "string | null",
    "evaluator_notes": "string | null"
  }
}`;

  const userText = `ANALYZER OUTPUT (literal JSON - read the field values exactly as written; do not paraphrase):
${analyzerOutput}

EXTRACTED CLINICAL FLAGS (literal JSON):
${extractionText}

TRANSCRIPT (for grounding):
${transcript || "(empty)"}`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(apiKey)}`;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 25000);

  let respJson;
  try {
    const resp = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: systemInstruction }] },
        contents: [{ role: "user", parts: [{ text: userText }] }],
        generationConfig: { responseMimeType: "application/json", temperature: 0.2 }
      }),
      signal: controller.signal
    });

    if (!resp.ok) {
      const errBody = await resp.text();
      throw new Error(`Gemini API error: ${resp.status} ${resp.statusText}. Body: ${errBody}`);
    }
    respJson = await resp.json();
  } catch (e) {
    if (e.name === "AbortError") throw new Error("Gemini evaluation timed out after 25s");
    throw e;
  } finally {
    clearTimeout(timeoutId);
  }
  const text = respJson.candidates?.[0]?.content?.parts?.[0]?.text || "";
  const cleaned = extractOutermostJson(text).trim();
  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch (parseErr) {
    // Log to Vercel function log so we can diagnose what Gemini actually returned.
    console.warn("EVALUATE PARSE FAILURE:", parseErr.message);
    console.warn("RAW RESPONSE (first 1500 chars):", text.slice(0, 1500));
    throw new Error(`Evaluator returned invalid JSON: ${parseErr.message}`);
  }
  if (!parsed?.evaluation) {
    console.warn("EVALUATE EMPTY EVALUATION:", JSON.stringify(parsed).slice(0, 500));
    throw new Error("Evaluator response did not include an 'evaluation' object.");
  }
  return { evaluation: parsed.evaluation, model };
}
